services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flights
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - flight_ops_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "flightopscookie"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - /home/boli/rabbitmq-data:/var/lib/rabbitmq   # <-- ruta nativa de WSL
    networks:
      - flight_ops_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  flight_service:
    build: ./src/flight_service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/flights
    networks:
      - flight_ops_net
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/flights"]
      interval: 15s
      timeout: 5s
      retries: 3

  booking_service:
    build: ./src/booking_service
    ports:
      - "8001:8001"
    networks:
      - flight_ops_net
    depends_on:
      flight_service:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/bookings"]
      interval: 15s
      timeout: 5s
      retries: 3

  notification_service:
    build: ./src/notification_service
    ports:
      - "8002:8002"
    networks:
      - flight_ops_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/notifications"]
      interval: 15s
      timeout: 5s
      retries: 3

networks:
  flight_ops_net:
    driver: bridge

volumes:
  pgdata:
